services:
  mongo:
    image: mongo
    env_file:
      - ./.env
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

  mongo-express:
    image: mongo-express
    env_file:
      - ./.env
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:${DATABASE_PASSWORD}@mongo:27017/