services:
  mongo:
    image: 'bitnami/mongodb'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=${DATABASE_PASSWORD}
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    env_file:
      - ./.env
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:${DATABASE_PASSWORD}@mongo:27017/